[package]
name = "react_compiler_ast"
description = "JavaScript AST types and transforms for the React Compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
react_compiler_diagnostics.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value", "unbounded_depth"] }
serde-transcode = "1"
indexmap = { version = "2", features = ["serde"] }
rustc-hash = "2"

[dev-dependencies]
walkdir = "2"
similar = "3"
