[package]
name = "react_compiler_validation"
description = "Validation passes for the React Compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
indexmap = "2"
rustc-hash = "2"
react_compiler_diagnostics.workspace = true
react_compiler_hir.workspace = true
