[package]
name = "react_compiler_reactive_scopes"
description = "Reactive scope inference for the React Compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
react_compiler_ast.workspace = true
react_compiler_diagnostics.workspace = true
react_compiler_hir.workspace = true
indexmap = "2"
rustc-hash = "2"
serde_json = "1"
hmac-sha256 = "1"
