[package]
name = "react_compiler_typeinference"
description = "Type inference passes for the React Compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rustc-hash = "2"
react_compiler_diagnostics.workspace = true
react_compiler_hir.workspace = true
react_compiler_ssa.workspace = true
