[package]
name = "react_compiler_ssa"
description = "SSA transformations for the React Compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
react_compiler_diagnostics.workspace = true
react_compiler_hir.workspace = true
indexmap = "2"
rustc-hash = "2"
